name: speedtodo_app
description: Speedtodo - 轻量高效的个人待办事项管理应用
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
